"""Tests for `implementation/runtime/golden_harness/evaluator_hash.py`
(T504, Piece 1) -- the evaluator-hash tamper-evidence check.

Three required categories per `docs/tasks/task-T504.md`'s "Expected
outputs" #6:

1. `TestRealRepoNoDrift` -- confirms no drift is reported against the real,
   current, unmodified repo state and the real, committed
   `docs/artifacts/evaluator-hash-known-good-v1.json` reference.
2. `TestDriftDetection` -- mutates a scratch copy of a protected-path file's
   content and confirms the check reports real, per-path drift.
3. `TestMalformedKnownGood` -- confirms only a structurally invalid
   known-good reference raises, never a mere digest mismatch.

No live agent session is invoked anywhere in this file.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from implementation.runtime.golden_harness import evaluator_hash as eh
from tests._helpers.repo import repo_root


class TestRealRepoNoDrift(unittest.TestCase):
    """Confirms the real, committed known-good reference matches the real,
    current, unmodified repo state -- proves the bootstrapped v1 value is
    actually correct, not merely well-formed."""

    def test_default_known_good_path_exists(self):
        self.assertTrue(eh.DEFAULT_KNOWN_GOOD_PATH.is_file())

    def test_no_drift_against_real_current_repo_state(self):
        result = eh.check_evaluator_hash()
        self.assertFalse(result.tests_golden_drift)
        self.assertFalse(result.scripts_scorecard_drift)
        self.assertFalse(result.any_drift)
        self.assertIn("NO DRIFT", result.reason)

    def test_compute_current_digests_is_deterministic_across_calls(self):
        first = eh.compute_current_digests()
        second = eh.compute_current_digests()
        self.assertEqual(first, second)

    def test_compute_current_digests_returns_two_independent_64_char_hex_digests(self):
        digests = eh.compute_current_digests()
        self.assertEqual(set(digests), {eh.DIGEST_KEY_TESTS_GOLDEN, eh.DIGEST_KEY_SCRIPTS_SCORECARD})
        for digest in digests.values():
            self.assertEqual(len(digest), 64)
            int(digest, 16)  # raises ValueError if not valid hex
        # The two protected paths have different real content, so their
        # digests must differ -- a real, non-tautological assertion.
        self.assertNotEqual(digests[eh.DIGEST_KEY_TESTS_GOLDEN], digests[eh.DIGEST_KEY_SCRIPTS_SCORECARD])


class TestDriftDetection(unittest.TestCase):
    """Mutates a *scratch copy* of a protected path's content (never the
    real tracked file) and confirms the check reports real, per-path
    drift."""

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="evaluator-hash-drift-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)
        # Copy the real protected paths into an isolated scratch repo root,
        # so mutating them never touches the real tracked tree. Excludes
        # __pycache__ explicitly (belt-and-suspenders with the git-tracked-
        # only fix below -- a fresh copytree of the real tree can itself
        # pick up locally-generated bytecode cache from prior test runs).
        real_root = repo_root()
        (self.tmp / "tests").mkdir(parents=True)
        shutil.copytree(
            real_root / "tests" / "golden",
            self.tmp / "tests" / "golden",
            ignore=shutil.ignore_patterns("__pycache__"),
        )
        (self.tmp / "scripts").mkdir(parents=True)
        shutil.copy(real_root / "scripts" / "scorecard.py", self.tmp / "scripts" / "scorecard.py")

        # A real (scratch, disposable) git repo, not just a plain directory
        # tree -- compute_path_digest now hashes git-tracked files only
        # (see evaluator_hash.py's own "load-bearing correctness fix"
        # docstring: a naive filesystem walk picks up untracked artifacts
        # like __pycache__, which would silently defeat a stable baseline).
        # This fixture must be a real git repo for the real code path to be
        # exercised, not a special-cased one.
        self._run_git("init", "--quiet")
        self._run_git("add", "-A")
        self._run_git("-c", "user.email=test@example.com", "-c", "user.name=Test", "commit", "--quiet", "-m", "seed")

        # The known-good reference for this scratch tree is computed from
        # its own (currently byte-identical-to-real, tracked-only) content.
        self.known_good_path = self.tmp / "known-good.json"
        payload = {
            "schema_version": 1,
            "algorithm": "sha256",
            "digests": eh.compute_current_digests(self.tmp),
            "computed_from_commit": "deadbeef",
            "computed_at": "2026-01-01T00:00:00Z",
        }
        self.known_good_path.write_text(json.dumps(payload), encoding="utf-8")

    def _run_git(self, *args: str) -> None:
        subprocess.run(["git", *args], cwd=self.tmp, check=True, capture_output=True, text=True)

    def test_no_drift_before_any_mutation(self):
        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertFalse(result.any_drift)

    def test_mutating_scorecard_reports_scripts_scorecard_drift_only(self):
        scorecard = self.tmp / "scripts" / "scorecard.py"
        scorecard.write_text(scorecard.read_text(encoding="utf-8") + "\n# tampered\n", encoding="utf-8")

        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertTrue(result.any_drift)
        self.assertTrue(result.scripts_scorecard_drift)
        self.assertFalse(result.tests_golden_drift)
        self.assertIn("scripts/scorecard.py", result.reason)
        self.assertNotIn("tests/golden", result.reason)

    def test_mutating_a_golden_case_file_reports_tests_golden_drift_only(self):
        target = self.tmp / "tests" / "golden" / "README.md"
        target.write_text(target.read_text(encoding="utf-8") + "\ntampered\n", encoding="utf-8")

        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertTrue(result.any_drift)
        self.assertTrue(result.tests_golden_drift)
        self.assertFalse(result.scripts_scorecard_drift)

    def test_mutating_both_paths_reports_both_drifted(self):
        (self.tmp / "scripts" / "scorecard.py").write_text("tampered entirely", encoding="utf-8")
        (self.tmp / "tests" / "golden" / "README.md").write_text("tampered entirely", encoding="utf-8")

        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertTrue(result.tests_golden_drift)
        self.assertTrue(result.scripts_scorecard_drift)
        self.assertTrue(result.any_drift)

    def test_adding_and_committing_a_new_file_under_tests_golden_is_detected_as_drift(self):
        # Drift includes additions, not just content edits to already-
        # tracked files -- but only once the addition is actually
        # git-tracked (see the next test for the untracked-file case,
        # which must NOT be reported as drift under the fixed design).
        new_file = self.tmp / "tests" / "golden" / "open" / "_new-adversarial-file.txt"
        new_file.parent.mkdir(parents=True, exist_ok=True)
        new_file.write_text("unexpected addition", encoding="utf-8")
        self._run_git("add", "-A")

        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertTrue(result.tests_golden_drift)

    def test_an_untracked_new_file_under_tests_golden_is_not_reported_as_drift(self):
        # The real reason compute_path_digest hashes git-tracked files only
        # (evaluator_hash.py's own "load-bearing correctness fix"): an
        # untracked file appearing on disk -- e.g. a __pycache__/.pyc
        # bytecode cache created by simply importing a case's expect.py --
        # must never register as tamper-evidence drift. This is the direct,
        # non-tautological proof that the fix actually achieves its stated
        # purpose, not merely that the old (now-removed) naive-walk
        # behavior changed.
        new_file = self.tmp / "tests" / "golden" / "open" / "_untracked-cache-like-file.pyc"
        new_file.parent.mkdir(parents=True, exist_ok=True)
        new_file.write_text("not committed, not tracked", encoding="utf-8")
        # Deliberately no `git add` here.

        result = eh.check_evaluator_hash(self.tmp, self.known_good_path)
        self.assertFalse(result.tests_golden_drift)
        self.assertFalse(result.any_drift)


class TestMalformedKnownGood(unittest.TestCase):
    """`check_evaluator_hash` raises only when the known-good reference file
    itself is structurally invalid -- never merely because of a digest
    mismatch (that's `TestDriftDetection`'s job, and it never raises)."""

    def setUp(self):
        self.tmp = Path(tempfile.mkdtemp(prefix="evaluator-hash-malformed-test-"))
        self.addCleanup(shutil.rmtree, self.tmp, ignore_errors=True)

    def test_missing_file_raises_value_error(self):
        with self.assertRaises(ValueError):
            eh.load_known_good(self.tmp / "does-not-exist.json")

    def test_malformed_json_raises_value_error(self):
        path = self.tmp / "bad.json"
        path.write_text("{not valid json", encoding="utf-8")
        with self.assertRaises(ValueError):
            eh.load_known_good(path)

    def test_missing_required_top_level_key_raises_value_error(self):
        path = self.tmp / "missing-key.json"
        path.write_text(json.dumps({"algorithm": "sha256", "digests": {"tests_golden": "a", "scripts_scorecard": "b"}}), encoding="utf-8")
        with self.assertRaises(ValueError):
            eh.load_known_good(path)  # missing computed_from_commit / computed_at

    def test_digests_missing_a_required_path_key_raises_value_error(self):
        path = self.tmp / "missing-digest.json"
        path.write_text(
            json.dumps(
                {
                    "algorithm": "sha256",
                    "digests": {"tests_golden": "a"},  # missing scripts_scorecard
                    "computed_from_commit": "x",
                    "computed_at": "y",
                }
            ),
            encoding="utf-8",
        )
        with self.assertRaises(ValueError):
            eh.load_known_good(path)

    def test_unsupported_algorithm_raises_value_error(self):
        path = self.tmp / "bad-algo.json"
        path.write_text(
            json.dumps(
                {
                    "algorithm": "md5",
                    "digests": {"tests_golden": "a", "scripts_scorecard": "b"},
                    "computed_from_commit": "x",
                    "computed_at": "y",
                }
            ),
            encoding="utf-8",
        )
        with self.assertRaises(ValueError):
            eh.load_known_good(path)

    def test_well_formed_reference_with_a_digest_mismatch_does_not_raise(self):
        # The load-bearing negative case: a purely structural loader accepts
        # this file; any drift it implies is reported by check_evaluator_hash,
        # never raised.
        path = self.tmp / "well-formed-but-wrong.json"
        path.write_text(
            json.dumps(
                {
                    "algorithm": "sha256",
                    "digests": {"tests_golden": "0" * 64, "scripts_scorecard": "1" * 64},
                    "computed_from_commit": "x",
                    "computed_at": "y",
                }
            ),
            encoding="utf-8",
        )
        loaded = eh.load_known_good(path)  # must not raise
        self.assertEqual(loaded["digests"]["tests_golden"], "0" * 64)

        result = eh.check_evaluator_hash(repo_root(), path)  # must not raise either
        self.assertTrue(result.any_drift)


class TestBuildKnownGoodPayload(unittest.TestCase):
    """`build_known_good_payload` builds (but never writes) the real
    bootstrap payload -- proving the module's construction helper is
    consistent with the check's own digest computation, and that it
    performs no filesystem write."""

    def test_payload_digests_match_compute_current_digests(self):
        root = repo_root()
        payload = eh.build_known_good_payload(root)
        self.assertEqual(payload["digests"], eh.compute_current_digests(root))
        self.assertEqual(payload["algorithm"], "sha256")
        self.assertTrue(payload["computed_from_commit"])
        self.assertTrue(payload["computed_at"])

    def test_matches_the_real_committed_known_good_reference(self):
        # The committed docs/artifacts/evaluator-hash-known-good-v1.json was
        # bootstrapped from this exact function -- confirm they still agree.
        root = repo_root()
        payload = eh.build_known_good_payload(root)
        committed = json.loads(eh.DEFAULT_KNOWN_GOOD_PATH.read_text(encoding="utf-8"))
        self.assertEqual(payload["digests"], committed["digests"])


if __name__ == "__main__":
    unittest.main()
